### PR TITLE
Kraken

### PR DESCRIPTION
**Pull request by tvb**
screen shot 2017-07-09 at 11 55 03

<sub>*note: I just finished the code so the graphs are not yet fully populated.</sub>

### CODE REVIEW

**Comment by nicka** [comment]
I'm sorry for the delay, I'll add some CI integration asap. Noticed some `var`'s and missing tests.

**Comment by tvb** [comment]
No worries @nicka. Maybe you can improve my code where it lacks quality. Tests is something I have to look into at a later day yes.

**Comment by nicka** [comment]
Please stick with one feature at a time. This is no longer only adding Kraken. I will work on the CI asap.

**Comment by tvb** [comment]
@nicka my bad. I might have f*cked up git merging 😊 I will reupload this feature asap.

**Comment by nicka** [comment]
No worries, thanks for the contributions.

**Pull request closed without merging**
