### PR TITLE
Adding Balance metrics

### PR DESCRIPTION
**Pull request by tvb**
With a lot of 💦 and 😢 I got it to work 😅

### CODE REVIEW

**Comment by tvb** [comment]
screen shot 2017-06-29 at 21 17 26

<sup>*note: gap in screenshot is due to a little boeboe I made</sup>

**Comment by tvb** [comment]
@nicka ping pong

**Comment by nicka** [comment]
@tvb May I know the use case for this? Please explain your end-goal 👍

**Comment by tvb** [comment]
@nicka Have my 💵  increase shown in a nice graph 😉

**Comment by nicka** [comment]
This is "just" showing your cryptocurrency balance. 

However it would be nice if we add logic which keeps track of existing transactions and it's buy/sell amounts. This way we can indeed show a graph with your profit/loss. What do you think?

**Comment by tvb** [comment]
@nicka yes I like that idea but perhaps as a added feature?

**Pull request closed without merging**
